global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090'] # self monitoring
  - job_name: 'fastapi-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:1234']


