# using python 3.12
FROM python:3.12

# COPY requirements.txt file to the /app directory
COPY ./app/requirements.txt /app/requirements.txt
COPY ./app/main.py /app/main.py

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

CMD ["python", "/app/main.py"]
